name: Build and Test Minimal API Discovery

on:
  push:
    branches: [ "main" ]
    paths:
      - src/Discovery/**
  pull_request:
    branches: [ "main" ]
    paths:
      - src/Discovery/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Discovery
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/Discovery
