name: Build and Test Minimal API Validation

on:
  push:
    branches: [ "main" ]
    paths:
      - src/FluentValidation/**
  pull_request:
    branches: [ "main" ]
    paths:
      - src/FluentValidation/**
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
          7.0.x
    - name: Restore dependencies
      working-directory: ./src/FluentValidation
      run: dotnet restore
    - name: Build
      working-directory: ./src/FluentValidation
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src/FluentValidation
      run: dotnet test --no-build --verbosity normal
